### ISSUE TITLE
Do you still have the missing 32-bit DOS driver sources under `msdos/pm_drvr/`?

### ISSUE THREAD

**Issue by volkertb** [gvanem/libpcap#1]
Hello @gvanem,

I hope you can help me.

The MS-DOS version of libpcap (that was removed from the upstream libpcap sources last year) could optionally be compiled with 32-bit network drivers, through the macro `USE_32BIT_DRIVERS`. You can see this at the top of `pcap-dos.c`:

```c
#if defined(USE_32BIT_DRIVERS)
  #include "msdos/pm_drvr/pmdrvr.h"
  #include "msdos/pm_drvr/pci.h"
  #include "msdos/pm_drvr/bios32.h"
  #include "msdos/pm_drvr/module.h"
  #include "msdos/pm_drvr/3c501.h"
  #include "msdos/pm_drvr/3c503.h"
  #include "msdos/pm_drvr/3c509.h"
  #include "msdos/pm_drvr/3c59x.h"
  #include "msdos/pm_drvr/3c515.h"
  #include "msdos/pm_drvr/3c90x.h"
  #include "msdos/pm_drvr/3c575_cb.h"
  #include "msdos/pm_drvr/ne.h"
  #include "msdos/pm_drvr/wd.h"
  #include "msdos/pm_drvr/accton.h"
  #include "msdos/pm_drvr/cs89x0.h"
  #include "msdos/pm_drvr/rtl8139.h"
  #include "msdos/pm_drvr/ne2k-pci.h"
#endif
```

Unfortunately, in every copy or fork of libpcap I've found so far (GitHub, DuckDuckGo, Google), the subdirectory `pm_drvr` is missing in `msdos`.

The file `readme.dos` offers the following clue:

```text
Note for djgpp users:
  If you got the libpcap from the official site www.tcpdump, then that
  distribution does NOT contain any sources for building 32-bit drivers.
  Instead get the full version at
     https://www.watt-32.net/pcap/libpcap.zip

  and set "USE_32BIT_DRIVERS = 1" in msdos\common.dj.
```

Unfortunately, the source distribution hosted at https://www.watt-32.net/pcap/libpcap.zip also doesn't have the `pm_drvr` sources. Instead, the `README.DOS` file in that zip file contains the same notice, but with yet another (apparently older) URL:

```text
Note for djgpp users:
  If you got the libpcap from the official site www.tcpdump, then that
  distribution does NOT contain any sources for building 32-bit drivers.
  Instead get the full version at
     http://home.broadpark.no/~gvanem/pcap/libpcap.zip

  and set "USE_32BIT_DRIVERS = 1" in msdos\common.dj.
```

Uh-oh, an insecure `http://` URL, apparently a home page hosted at a user's ISP, that looks quite ancient. Let's hope that link still works... Aaaaand of course it doesn't.

So I entered that URL in the Internet Archive, hoping that it was cached by the Wayback Machine at one point... :crossed_fingers:  And although the Internet Archive has helped me out in quite a few situations, unfortunately it never cached this particular URL. :disappointed:

Since that old broadpark.no link has your username behind the tilde, and you do have a libpcap fork on GitHub, I was hoping you could perhaps help me find these missing `pm_drvr` sources.

It's not even specifically the NIC drivers I'm interested in. I'm particularly keen to obtain the PCI and BIOS32 sources in that folder (both the headers and C implementations).

The reason why I'm looking for these sources: for a project that is unrelated to libpcap, I'm trying to call a BIOS32 service (specifically PCI) from protected mode, in a DOS (DPMI) application that I'm building with DJGPP. I've ported some BIOS32 sources from NetBSD, and I've gotten so far as to detect and locate the entrypoint of the BIOS32 service, but whenever I try to perform a far call to the entrypoint from my DJGPP application, I'm getting a General Protection Fault. I could try to debug this, but it's an inline assembly function that's causing the fault (the actual far call), which isn't easy to debug. It would save me a lot of time if I had access to existing open source software that already did the same thing in a DJGPP project. After a search on GitHub, `pcap-dos.c` was the only other project that I could find that also accessed BIOS32 from DOS (or DPMI), but for that it does depend on`bios32.h` and whatever C code implements it and compiles to `bios32.o`.

Do you still have these `pm_drvr` sources, by any chance? Because they appear to have completely disappeared from the face of the Earth. And if you do, how are these sources licensed? Is the license perhaps the reason why these sources were excluded from the upstream libpcap sources in the first place?

Thank you kindly for any help you can provide me with this. :slightly_smiling_face:

**Comment by gvanem** [comment]
I emailed a .zip to your private email. But got this in response:
```
Sorry, we were unable to deliver your message to the following address.

<xx@yy.zz>:
550: 5.7.1 Sanesecurity.Foxhole.Zip_exe.UNOFFICIAL detected
```

Hence attached here: 
[pcap-msdos.zip](https://github.com/gvanem/libpcap/files/13857661/pcap-msdos.zip)

**Comment by volkertb** [comment]
Thank you very much for sharing!

However, could you please remove the email address from the response that you shared above, to prevent it from being harvested by spam bots? Thanks. 🙏

I uploaded the ZIP file to [VirusTotal, where 3 malware scanner engines flagged a trojan in the file](https://www.virustotal.com/gui/file/aaf12f661da86d729c35ee661ed5929d0083f11f81520fb732c238bb1bfe75ac). Probably heuristic scanners that were overly cautious about the low-level nature of some of the routines. That probably explains why my email provider blocked the attachment.

**Comment by gvanem** [comment]
> However, could you please remove the email address from the response 

Done.

**Comment by volkertb** [comment]
Thanks again. 🙂 I took a quick look and it would appear that these sources are licensed under GPLv2. For my purposes, that's fine. Was this the reason why these sources were left out of the upstream pcap sources, which are licensed under the more permissive 3-clause BSD license?

Also, would you have any objections against me pushing the contents of this ZIP file to a separate public GitHub repo?

**Comment by gvanem** [comment]
> Also, would you have any objections against me pushing the contents of this ZIP file to a separate public GitHub repo?

Not at all. Which one?

**Comment by volkertb** [comment]
I was thinking a new and dedicated repo for these sources, for historic reference. At that point, I'll copy the BIOS32 and PCI stuff for use in another project of mine: https://github.com/volkertb/ail32-ich (which I'll probably have to relicense in order to allow for that).

I might also try to create a PR for the pciutils project to add the BIOS32 PCI service access method to it. Although pciutils is licensed as "GPLv2 or higher", and this code appears to be licensed as "GPLv2 only", so that might not be feasible for that reason.

**Comment by volkertb** [comment]
Unpacked and pushed it here: https://github.com/volkertb/pcap-msdos

With that, I'm marking this issue as resolved. :slightly_smiling_face:
